version: "3.9"

services:
  api:
    image: noveb/battlesnake
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build_type: development
      target: test
      cache_from:
        - node:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      TIMEZONE: UTC
    ports:
      - 9000:5000
      - 9229:9229
    networks:
      - bs_network
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./nodemon.json:/app/nodemon.json
      - ./jest.config.ts:/app/jest.config.ts
      - ./src:/app/src
    command: npm run test:watch

networks:
  bs_network:
    driver: bridge
