FROM alpine:latest

RUN apk update && apk upgrade

RUN apk add curl tar bash

WORKDIR /root

RUN curl -L https://github.com/battlesnakeio/engine/releases/download/v0.2.23/engine_0.2.23_Linux_x86_64.tar.gz | tar zxv

EXPOSE 3010/tcp
EXPOSE 3010/udp

ENTRYPOINT ["./engine", "dev"]