version: "3"

services:
  api:
    build: ./src/
    ports:
      - "9001:5000"
    depends_on:
      - mongo
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - "8081:8081"